version: 1.2

workflows:
  - name: AmpSeq
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/wdl_ampseq.wdl
  - name: MHap
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/wdl_report_layouting.wdl
